root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  # Aqui está a definição para o binário Unix-like (sem extensão .exe)
  bin_unix = "./cmd/server"  # O caminho para o binário Unix-like
  cmd_unix = "GOOS=linux go build -o ./cmd/server ./cmd/server/main.go"  # Certifique-se de que está apontando para o arquivo main.go correto

  # Aqui está a definição para o binário Windows (.exe)
  bin_windows = "./cmd/server.exe"  # O caminho para o binário Windows
  cmd = "go build -o ./tmp/main.exe ./cmd/server/main.go"

  
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = [".", "internal"]  # Inclui o diretório internal para observação
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
