name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Build the project
    - name: Build
      run: go build -v ./...

    # Run tests
    - name: Test
      run: go test -v ./...

    # Run linters (optional)
    - name: Run golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run

    # Run test coverage (optional)
    - name: Test coverage
      run: go test -coverprofile=coverage.out ./...

    # Upload coverage report to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Adicione o token do Codecov como um segredo
        files: coverage.out  # Corrigir de "file" para "files"
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
